openapi: 3.0.0

info:
  title: ElasticSearch database API 
  version: "1.0"

servers:
  - url: http://128.174.136.27:8080/v1
 
paths:
  /search_author_name:
      get:
        tags:
        - public
        operationId: resolve.search_author_name
        parameters:
          - in: query
            name: author_name
            schema:
              type: string
            required: true 
            description: Name of the author
        responses:
          '200':
            description: OK
            content:
              applicatoin/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Author'
  
  /search_author_name_affiliation:
      get:
        tags:
        - public
        operationId: resolve.search_author_name_affiliation
        parameters:
          - in: query
            name: author_name
            schema:
              type: string
            required: true 
            description: Name of the author
          - in: query
            name: author_affiliation
            schema:
              type: string
            required: true
            description: Affiliation of the author
        responses:
          '200':
            description: OK
            content:
              applicatoin/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Author'


components:
  schemas:
    Author:
      type: object
      properties:
        AuthorId:
          type: string
        Rank:
          type: string
        NormalizedName:
          type: string
        DisplayName:
          type: string
        LastKnownAffiliationId:
          type: string
        PaperCount:
          type: string
        PaperFamilyCount:
          type: string
        CitationCount:
          type: string
        CreatedDate:
          type: string
    Affiliation:
      type: object
      properties:
        AffiliationId:
          type: string
        Rank:
          type: string
        NormalizedName:
          type: string
        DisplayName:
          type: string
        GridId:
          type: string
        OfficialPage:
          type: string
        WikiPage:
          type: string
        PaperCount:
          type: string
        PaperFamilyCount:
          type: string
        CitationCount:
          type: string
        Iso3166Code:
          type: string
        Latitude:
          type: string
        Longitude:
          type: string
        CreatedDate:
          type: string

   
      