openapi: 3.0.0

info:
  title: ElasticSearch database API 
  version: "1.0"

servers:
  - url: http://128.174.136.27:8080/v1
 
paths:
  /search_affiation:
      get:
        tags:
        - public
        operationId: resolve.search_affiliation
        description: Search for affiliations
        parameters:
          - in: query
            name: affiliation_name
            schema:
              type: string
            required: true 
            description: Name of the affiliation
          - in: query
            name : size 
            schema:
              type: integer
            description: max number of paper to search for, default to 1
        responses:
          '200':
            description: OK
            content:
              applicatoin/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Affiliation'

  /search_author:
      get:
        tags:
        - public
        operationId: resolve.search_author_name_affiliation
        description: Search for authors
        parameters:
          - in: query
            name: author_name
            schema:
              type: string
            required: true 
            description: Name of the author
          - in: query
            name: author_affiliation
            schema:
              type: string
            description: Affiliation of the author
          - in: query
            name : size 
            schema:
              type: integer
            description: max number of paper to search for, default to 1 if both name and affiliation are provided, otherwise default to 10
        responses:
          '200':
            description: OK
            content:
              applicatoin/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Author'

  /search_paper:
      get:
        tags:
        - public
        description: Search for papers <br> Provide <br> 1. author name and/or author affiliation to search for papers of the author, or <br> 2. paperID for exact search of paper, or <br> 3. title of paper
        operationId: resolve.search_author_for_paper
        parameters:
          - in: query
            name: author_name
            schema:
              type: string
            description: Name of the author
          - in: query
            name: author_affiliation
            schema:
              type: string
            description: Affiliation of the author
          - in: query
            name: paperID
            schema:
              type: string
            description: ID of the paper
          - in: query
            name: paper_title
            schema:
              type: string
            description: title of the paper
          - in: query
            name : size 
            schema:
              type: integer
            description: max number of paper to search for, default to 10
        responses:
          '200':
            description: OK
            content:
              applicatoin/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Paper'
          '400':
            description: Bad request.         
  
  /search_reference_paper:
      get:
        tags:
          - public
        operationId: resolve.search_reference_paper
        description: Searches for the papers referenced by/referencing the given paper
        parameters:
          - in: query
            name: paperID
            schema:
              type: string
            required: true 
            description: ID of the paper
          - in: query
            name: num_paper
            schema:
              type: integer 
            description: Number of reference paper to be searched
          - in: query
            name: cited_by_papers
            schema:
              type: boolean 
            description: Indicator of whether papers referencing the given paper is wanted, default to False meaning paper referenced by the given paper are returned  
          - in: query
            name : size 
            schema:
              type: integer
            description: max number of paper to search for, default to 10
        responses:
          '200':
            description: OK
            content:
              applicatoin/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Paper'                                                                                                                                                                 


components:
  schemas:
    Author:
      type: object
      properties:
        AuthorId:
          type: string
        Rank:
          type: string
        NormalizedName:
          type: string
        DisplayName:
          type: string
        LastKnownAffiliationId:
          type: string
        PaperCount:
          type: string
        PaperFamilyCount:
          type: string
        CitationCount:
          type: string
        CreatedDate:
          type: string
    Affiliation:
      type: object
      properties:
        AffiliationId:
          type: string
        Rank:
          type: string
        NormalizedName:
          type: string
        DisplayName:
          type: string
        GridId:
          type: string
        OfficialPage:
          type: string
        WikiPage:
          type: string
        PaperCount:
          type: string
        PaperFamilyCount:
          type: string
        CitationCount:
          type: string
        Iso3166Code:
          type: string
        Latitude:
          type: string
        Longitude:
          type: string
        CreatedDate:
          type: string
    Paper:
      type: object
      properties:
        PaperId:
          type: string
        Rank:
          type: string
        Doi:
          type: string
        DocType:
          type: string
        PaperTitle:
          type: string
        OriginalTitle:
          type: string
        BookTitle:
          type: string
        Year:
          type: string
        Date:
          type: string
        OnlineDate:
          type: string
        Publisher:
          type: string
        JournalId:
          type: string
        ConferenceSeriesId:
          type: string
        ConferenceInstanceId:
          type: string
        Volume:
          type: string
        Issue:
          type: string
        FirstPage:
          type: string
        LastPage:
          type: string
        ReferenceCount:
          type: string
        CitationCount:
          type: string
        EstimatedCitation:
          type: string
        OriginalVenue:
          type: string
        FamilyId:
          type: string
        FamilyRank:
          type: string
        DocSubTypes:
          type: string
        CreatedDate:
          type: string
  


   
      